# Docker Compose para PostgreSQL

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ["Ingrese usuario de la base de datos"]
      POSTGRES_PASSWORD: ["Ingrese contraseña de la base de datos"]
      POSTGRES_DB: ["Ingrese nombre de la base de datos"]
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/scripts:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d actividad_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./proyecto-base-de-datos
    container_name: next_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ["Ingrese host de la base de datos"]
      DB_PORT: ["Ingrese puerto de la base de datos"]
      DB_USER: ["Ingrese usuario de la base de datos"]
      DB_PASSWORD: ["Ingrese contraseña de la base de datos"]
      DB_NAME: ["Ingrese nombre de la base de datos"]
      NODE_ENV: 
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
